[package]
name = "minitoc"
version = "0.1.1"
description = "An outline function just for one section and nothing else"
authors = ["nxe <@RosiePuddles>", "sdiebolt <@sdiebolt>"]
license = "GPL-3.0-only"
entrypoint = "lib.typ"
respository = "https://github.com/sdiebolt/minitoc"
